### ISSUE TITLE
[Enhancement] Freeze two variables at once.

### ISSUE THREAD

**Issue by timfaner** [Qwokka/Cetus#29]
Freeze more than one variables at once . It is useful to handle time related variables

**Comment by Qwokka** [comment]
Added to the v1.1 milestone, thanks!

**Comment by timfaner** [comment]
Cool, are there any roadmap for v1.1 ?

**Comment by Qwokka** [comment]
It's in the works but I haven't had much time to work lately. Tigran, the UI designer, finished a big overhaul that I need to finish implementing, but that's a huge roadblock out of the way for 1.1 at least.

**Comment by Markkop** [comment]
Hey, @Qwokka. This extension is great, nice work!
I was looking on how could I contribute to have this multiple variables freezing, but couldn't find an easy way to implement it. It looks like that setting `MAX_WATCHPOINTS` to more than 1 should work, but it might be missing some extra code, idk.
Let me know if you have an idea on how can I help

**Comment by Qwokka** [comment]
Hi Marcelo,

Thanks for asking about this. Thanks for taking the time to take a look at
this! Unfortunately it's a bit complicated to do this in an efficient way.
Essentially, as it's done right now a single watchpoint consists of:

4 GLOBAL entries:
    - One containing the address being watched
    - One containing the "known" value at the address
    - One containing the size of being watched (1, 2, 4, or 8 bytes)
    - One containing a set of flags that define what the watchpoint should
do (Trigger on read, trigger on write, and/or freeze)

The functionality of the watchpoint is implemented by inserting
instructions with each load or store instruction. So for example, an
"i32.store" instruction would have the following instructions injected
after it:

get_global [watchpoint flags]
if
    call [injected watchpoint function]
end

This manages to be reasonably efficient because we don't even enter the
function that implements the core functionality of the watchpoint unless we
know for sure the watchpoint is enabled.

The trouble occurs when you try to support multiple watchpoints at once. If
we were to just duplicate this process, the performance impact would be X
times as much (Where X is the amount of watchpoints we choose to support).

I think a better scaling approach might look something like this:

1. Create 2 more globals we could refer to as "areWriteWatchpointsEnabled"
and "areReadWatchpointsEnabled" and set/unset them as necessary. This way
the code injected into a load instruction won't execute if only write
watchpoints are enabled, and the same for store instructions.
2. Store watchpoint flags in a single 64-bit global. This should allow us
to support up to 21 (3 bits per watchpoint * 21 = 63 bits used) watchpoints
at once, which seems like it should be more than enough for normal usage.
3. Refactor the read and write watchpoint callback functions to handle up
to 21 watchpoints in the most efficient way possible.

Apologies for the long read, it was helpful for me to get this down in
writing.

Jack

**Comment by Qwokka** [comment]
This is now doable as of 293adc09ea6140ca6dbe4b51ca4c2d353e99e16e. By default you can use up to 3 watchpoints at once, but this can be increased to up to 10 from the extension options.

Jack
